app: ClsToAPI
component: scf
inputs:
  description: Cls to API
  eip: false
  environment:
    variables:
      API_Key: 123
      URL: topic
  events:
    - cls:
        parameters:
          enable: true
          qualifier: $DEFAULT
          topicId: f5ca2b54-be89-47dd-9aca-a55b7db691e3
  handler: index.main_handler
  initTimeout: 65
  memorySize: 512
  msgTTL: 21600
  name: ClsToAPI
  namespace: default
  publicAccess: true
  region: ap-chengdu
  retryNum: 0
  runtime: Python3.6
  src: ./
  timeout: 10
  type: event
name: ap-chengdu_default_ClsToAPI
org: '1307427535'
stage: dev
# When using this configuration file for deployment, make sure the file name is "serverless.yml".
# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md